const ADD_USER = "ADD_USER",
    REMOVE_USER = "REMOVE_USER",
    ADD_POST = "ADD_POST",
    REMOVE_POST = "REMOVE_POST",
    ADD_COMMENT = "ADD_COMMENT",
    ADD_LIKE = "ADD_LIKE",
    REMOVE_LIKE = "REMOVE_LIKE",
    ADD_MESSAGE = "ADD_MESSAGE"
